import React from 'react'
import './ProjectContainer.css'
import { Element } from 'react-scroll'
import Project from '../Project/Project.js';
import Legacy from '../../assets/legacy.png'
import Adintel from '../../assets/nielsenadintel 2.0.jpg'

const ProjectContainer = () => {

    const projects = [
        {
            img:Legacy,
            title:"Nielsen Adintel Legacy",
            desc:
            "This web-based application provides its users with insights into competitive advertisement information across different local markets on various platforms.The reports which were generated by this can alert the stack-holders with new sales information and makes it easy to interpret data for addressing most of the competitive questions.",
            link:"https://adintel.global.nielsen.com/AdIntelUI/login.aspx?redirect=%2fadintelui"
            
        },
        {
            img:Adintel,
            title:"Nielsen Adintel 2.0",
            desc:
            "ADINTEL project delivers an integrated client delivery platform for all the Nielsen clients globally with a real-time capability of generating the reports based on the user selections.",
            link:"https://markets.nielsen.com/us/en/client-learning/tv/national/ad-intel/"
        }
    ];

  return (
    <Element className='projectContainer' id='projects'>
        <h1>Projects</h1>
        <p>Here are some projects I have worked in Tata Consultancy Service</p>
        <div className='projectContainer__projects'>
        {
            projects.map((project,index)=>{
                return(
                    <Project key={index} img={project.img} title={project.title} desc={project.desc} link={project.link} />
                );
            })
        }
        </div>
    </Element>
  );
}

export default ProjectContainer;
